INSERT INTO `items` (
  `slug`,
  `name`,
  `description`,
  `category`,
  `source_region_id`,
  `source_family_slug`,
  `rarity`,
  `is_stackable`,
  `is_visible_before_discovery`,
  `is_spendable`,
  `is_primary_progression`,
  `icon_key`,
  `lore_key`,
  `meta_json`
)
VALUES
(
  'field_poultice',
  'Field Poultice',
  'A quick wrap for patching up a wounded unit between encounters.',
  'consumable',
  NULL,
  NULL,
  'common',
  1,
  1,
  1,
  0,
  'item_field_poultice',
  'healing_consumable',
  JSON_OBJECT('effect', JSON_OBJECT('type', 'heal_run_unit_hp', 'amount', 10))
),
(
  'hearty_bone_broth',
  'Hearty Bone Broth',
  'A stronger recovery draught that brings one run unit back from the edge.',
  'consumable',
  NULL,
  NULL,
  'uncommon',
  1,
  1,
  1,
  0,
  'item_hearty_bone_broth',
  'healing_consumable',
  JSON_OBJECT('effect', JSON_OBJECT('type', 'heal_run_unit_hp', 'amount', 25))
)
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `description` = VALUES(`description`),
  `category` = VALUES(`category`),
  `source_region_id` = VALUES(`source_region_id`),
  `source_family_slug` = VALUES(`source_family_slug`),
  `rarity` = VALUES(`rarity`),
  `is_stackable` = VALUES(`is_stackable`),
  `is_visible_before_discovery` = VALUES(`is_visible_before_discovery`),
  `is_spendable` = VALUES(`is_spendable`),
  `is_primary_progression` = VALUES(`is_primary_progression`),
  `icon_key` = VALUES(`icon_key`),
  `lore_key` = VALUES(`lore_key`),
  `meta_json` = VALUES(`meta_json`);
