import { AudioManifestEntry } from './audio.models';

export const AUDIO_MANIFEST: readonly AudioManifestEntry[] = [
  {
    key: 'ui.click',
    category: 'ui',
    sources: [],
    defaultVolume: 0.8,
    loop: false,
    preload: 'eager',
    cooldownMs: 40,
    description: 'Primary UI click feedback.',
  },
  {
    key: 'ui.confirm',
    category: 'ui',
    sources: [],
    defaultVolume: 0.9,
    loop: false,
    preload: 'eager',
    cooldownMs: 80,
    description: 'Confirmation and accept actions.',
  },
  {
    key: 'ui.cancel',
    category: 'ui',
    sources: [],
    defaultVolume: 0.75,
    loop: false,
    preload: 'eager',
    cooldownMs: 80,
    description: 'Cancel and dismiss actions.',
  },
  {
    key: 'music.login',
    category: 'music',
    sources: [],
    defaultVolume: 0.6,
    loop: true,
    preload: 'route',
    stream: true,
    description: 'Login and unauthenticated shell music intent.',
  },
  {
    key: 'music.home',
    category: 'music',
    sources: [],
    defaultVolume: 0.62,
    loop: true,
    preload: 'route',
    stream: true,
    description: 'Home and camp management music intent.',
  },
  {
    key: 'music.regions',
    category: 'music',
    sources: [],
    defaultVolume: 0.62,
    loop: true,
    preload: 'route',
    stream: true,
    description: 'Region selection and run preparation music intent.',
  },
  {
    key: 'music.run',
    category: 'music',
    sources: [],
    defaultVolume: 0.58,
    loop: true,
    preload: 'route',
    stream: true,
    description: 'Run map and route traversal music intent.',
  },
  {
    key: 'music.battle.normal',
    category: 'music',
    sources: [],
    defaultVolume: 0.68,
    loop: true,
    preload: 'route',
    stream: true,
    description: 'Standard combat playback music intent.',
  },
  {
    key: 'music.battle.boss',
    category: 'music',
    sources: [],
    defaultVolume: 0.72,
    loop: true,
    preload: 'route',
    stream: true,
    description: 'Boss combat playback music intent.',
  },
  {
    key: 'music.summary',
    category: 'music',
    sources: [],
    defaultVolume: 0.58,
    loop: true,
    preload: 'route',
    stream: true,
    description: 'Run summary and rewards music intent.',
  },
];

export const AUDIO_MANIFEST_BY_KEY = new Map<string, AudioManifestEntry>(
  AUDIO_MANIFEST.map((entry) => [entry.key, entry]),
);
